# Change these first
owner: yamagami2211 # Your GitHub username
repo: site-kanshi # Your GitHub repository name

# Add your sites here
sites:
  - name: SV2
    url: http://sv02-vps.yama2211.jp

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.yama2211.jp
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /site-kanshi
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Server Status
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Site
      href: https://yama2211.jp/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

#CommitUser
commitMessages:
  commitAuthorName: "site-kanshi"
  commitAuthorEmail: "site-kanshi@yama2211.jp"

# 40 - 81 Line : WebSite
# 82 - 104 Line : Readme.md
i18n:
  activeIncidents: "有効なインシデント"
  incidentReport: "インシデントレポート #$NUMBER→"
  activeIncidentSummary: "$DATE にオープン 投稿数 $POSTS"
  incidentTitle: "インシデント #$NUMBER の詳細"
  incidentDetails: "インシデントの詳細"
  incidentFixed: "修正"
  incidentOngoing: "進行中"
  incidentOpenedAt: "オープン"
  incidentClosedAt: "クローズ"
  incidentSubscribe: "アップデートを購読する"
  incidentViewOnGitHub: "GitHubで表示"
  incidentCommentSummary: "投稿日時$DATE 投稿者 $AUTHOR"
  incidentBack: "←すべてのインシデントに戻る"
  pastIncidents: "過去のインシデント"
  pastIncidentsResolved: "$MINUTES 分で解決 投稿数 $POSTS"
  liveStatus: "現在の状態"
  overallUptime: "全体の稼働率: $UPTIME"
  overallUptimeTitle: "全体の稼働率"
  averageResponseTime: "平均応答時間: $TIMEms"
  averageResponseTimeTitle: "平均応答時間"
  sevelDayResponseTime: "7日間の応答時間"
  loading: "読込中"
  navGitHub: "GitHub"
  footer: "このページは[オープンソース]($REPO)で、[Upptime](https://upptime.js.org)を利用して  います。"
  rateLimitExceededTitle: "レート制限を超えました"
  rateLimitExceededIntro: "1時間に実行できるリクエストの数を超えたため、このWebサイトに再度ア  クセスする前に待機する必要があります。 または、GitHubパーソナルアクセストークンを追加して、こ  のWebサイトを引き続き使用することもできます。"
  rateLimitExceededWhatDoesErrorMean: "このエラーはどういう意味ですか？"
  rateLimitExceededErrorMeaning: "このウェブサイトは、GitHub APIを使用して、ウェブサイトのステ  ータスに関するリアルタイムデータにアクセスします。 デフォルトでは、GitHubは各IPアドレスに1時  間あたり60リクエストを許可します。"
  rateLimitExceededErrorHowCanFix: "どうすれば修正できますか？"
  rateLimitExceededErrorFix: "さらに1時間待つと、IPアドレスの制限が復元されます。 または、  GitHubパーソナルアクセストークンを追加して、1時間あたり5,000件のリクエストを追加することもで  きます"
  rateLimitExceededGeneratePAT: "パーソナルアクセストークンを生成する方法を学ぶ"
  rateLimitExceededHasSet: "パーソナルアクセストークンセットがあります。"
  rateLimitExceededRemoveToken: "トークンを削除する"
  rateLimitExceededGitHubPAT: "GitHubパーソナルアクセストークン"
  rateLimitExceededCopyPastePAT: "トークンをコピーして貼り付けます"
  rateLimitExceededSaveToken: "トークンを保存"
  errorTitle: "エラーが発生しました"
  errorIntro: "最新のステータスの詳細を取得しようとしてエラーが発生しました。"
  errorText: "しばらくしてからもう一度お試しください。"
  errorHome: "ホームページに移動"
  pastScheduledMaintenance: 過去の定期メンテナンス
  scheduledMaintenance: 定期メンテナンス
  scheduledMaintenanceSummaryStarted: $DATA $DURATION分間
  scheduledMaintenanceSummaryStarts: $DATA $DURATION分
  startedAt: 開始日
  startsAt: に始まる
  duration: 期限
  durationMin: $DURATION 分
  incidentCompleted: 完了
  incidentScheduled: 予定
  url: "URL"
  status: "状態"
  history: "履歴"
  uptime: "稼働時間"
  up: "🟩 正常"
  degraded: "🟨 低下"
  down: "🟥 停止"
  responseTimeGraphAlt: "応答時間グラフ"
  ms: "ミリ秒"
  responseTime: "応答時間"
  responseTimeDay: "24時間 応答時間"
  responseTimeWeek: "7日 応答時間"
  responseTimeMonth: "30日 応答時間"
  responseTimeYear: "1年 応答時間"
  uptimeDay: "24時間の稼働時間"
  uptimeWeek: "7日間の稼働時間"
  uptimeMonth: "30日の稼働時間"
  uptimeYear: "1年の稼働時間"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "🟩 すべてのシステムは正常に稼働"
  degradedPerformance: "🟨 パフォーマンスの低下"
  completeOutage: "🟥 完全な停止"
  partialOutage: "🟧 部分的な停止"
